---
common:
  ssh_key_name: vaijab
  coreos_ami_name: CoreOS-alpha-752.1.0-hvm
  compute_min_instances: 3
  vpc_cidr: 10.50.0.0/16
  compute_subnets:
    - 10.50.0.0/24
    - 10.50.1.0/24
    - 10.50.2.0/24
  # this is where etcd and vault lives
  secure_subnets:
    - 10.50.10.0/24
    - 10.50.11.0/24
    - 10.50.12.0/24
  etcd_nodes:
  - name: EtcdNode0
    ip: 10.50.10.200
    az_id: '0'
  - name: EtcdNode1
    ip: 10.50.10.201
    az_id: '0'
  - name: EtcdNode2
    ip: 10.50.11.200
    az_id: '1'
  - name: EtcdNode3
    ip: 10.50.11.201
    az_id: '1'
  - name: EtcdNode4
    ip: 10.50.12.200
    az_id: '2'
  flannel_cidr: 10.10.0.0/16

prod:
  vpc_name: prod-vpc
  infra_stack_name: prod-infra
  instance_type: t2.large
dev:
  vpc_name: dev-vpc
  infra_stack_name: dev-infra
  instance_type: t2.medium
  dns_zone_name: dsp.notprod.homeoffice.gov.uk
  kms_master_key_id: 448a33c3-694b-46fe-9635-4cfecff6877a
  secrets_bucket_name: dev-platform-secrets-eu-west-1
  # base64 encoded
  ca_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrakNDQXVLZ0F3SUJBZ0lJWEsxWXRRTzdSZVV3RFFZSktvWklodmNOQVFFTEJRQXdnWWd4Q3pBSkJnTlYKQkFZVEFrZENNUnd3R2dZRFZRUUtFeE5JYjIxbElFOW1abWxqWlNCRWFXZHBkR0ZzTVJ3d0dnWURWUVFMRXhORQpVMUFnUkdWMklFVnVkbWx5YjI1dFpXNTBNUTh3RFFZRFZRUUhFd1pNYjI1a2IyNHhEekFOQmdOVkJBZ1RCa3h2CmJtUnZiakViTUJrR0ExVUVBeE1TU0c5dFpTQlBabVpwWTJVZ1JGTlFJRU5CTUI0WERURTFNRGN5TURFNE1qWXcKTUZvWERUSTFNRGN4TnpFNE1qWXdNRm93Z1lneEN6QUpCZ05WQkFZVEFrZENNUnd3R2dZRFZRUUtFeE5JYjIxbApJRTltWm1salpTQkVhV2RwZEdGc01Sd3dHZ1lEVlFRTEV4TkVVMUFnUkdWMklFVnVkbWx5YjI1dFpXNTBNUTh3CkRRWURWUVFIRXdaTWIyNWtiMjR4RHpBTkJnTlZCQWdUQmt4dmJtUnZiakViTUJrR0ExVUVBeE1TU0c5dFpTQlAKWm1acFkyVWdSRk5RSUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNlkycQpSSjBDMlJwb0s0elhiWDhBMTNEVGRtRFRHUlZsd3kxQnpZTUpsQTRUelFRdGZrS2NRYzY5clZGUmkxN1hrQ0NxCk5XYW9IeHhqRTAvcnA3bDBueGNncGxWdURrMVZLSVhsemVKdVUzaWE2Ky9RWHI4M3lacENRRlBwK3N5R0pGeXIKMjFXa2NrK0xDdGJuN1I4Kzk0RzV4MzNNZWQyemg5SEczZG5DbHZlQWFJTlRhUnlTZU9Yb0RLRTVLUHZ2RlpxQwo4L0hQUzJCZWI4TFRXbFNQUWM3dHNMc3UxMy8rS3FhZXVtV2hZcVZXZDFHdiszc2JLUGZLcFlSRURlQXpGelpjCkVpa0tYWjQ0MjlDTHRSN1l4WkFKbFdoWFdrbDN2cDB4bStBd2VDMlNmajJsbjR5TGR5YjkxLy9oYnFkRUJwak0Ka09RZEZNNERibWFaNkdRKzRRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFILwpCQWd3QmdFQi93SUJBakFkQmdOVkhRNEVGZ1FVRTVDTnlUT21PYW9zbjY2clRQL3ozWDAwQW5rd0h3WURWUjBqCkJCZ3dGb0FVRTVDTnlUT21PYW9zbjY2clRQL3ozWDAwQW5rd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNYzkKUDhCL1JYREJZTjVtZyt5NjR4Zm4xR0drZUJCYUVVRTdjeHRYWEEyN2dSWVB5SUU5cENRdXI3YlMzWnQyMmtEMQp3SGlMUWdmb056Y2NYcTV2QUdPRGFYWVRTczVQMllnU2NMZ0xOVktGUnRtQWd4L2hJRDUxSFYzMTkwTDlnTDFSCm1NSXViUmczNDNTaWI4WElQQlorODhGZkhmUWd3TkpuK3F6NzRtWmpudi8rTTVoTFU4cXhrb24xTTFWQlhCVmIKTVU1cWtkOGw3SnZBMlJia0xrYWxMdks5U3NJTWJLQ3hwckRZY2thUjlHWGhnNUhsTlExWUd4Y1dHSWZVK1Z0aQp3RXVhY0tPRFQ3dlNKdko0YTl3WXBOREkwMEVUZDJVNXBQYVpLSVdqLy9XNSszMHNtL0h2Z3MwNmJTUE9nMDBOCjJvU1V6SGZiWjB4NkkxQWxqcnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

