---
common:
  ssh_key_name: vaijab
  coreos_ami_name: CoreOS-alpha-794.0.0-hvm
  compute_min_instances: 5
  vpc_cidr: 10.50.0.0/16
  compute_subnets:
    - 10.50.0.0/24
    - 10.50.1.0/24
    - 10.50.2.0/24
  # this is where etcd and vault lives
  secure_subnets:
    - 10.50.10.0/24
    - 10.50.11.0/24
    - 10.50.12.0/24
  etcd_nodes:
  - name: EtcdNode0
    ip: 10.50.10.200
    az_id: '0'
  - name: EtcdNode1
    ip: 10.50.10.201
    az_id: '0'
  - name: EtcdNode2
    ip: 10.50.11.200
    az_id: '1'
  - name: EtcdNode3
    ip: 10.50.11.201
    az_id: '1'
  - name: EtcdNode4
    ip: 10.50.12.200
    az_id: '2'
  flannel_cidr: 10.10.0.0/16
  ssh_access_subnets:
  - 80.193.85.91/32
  - 80.169.158.34/32
  kube_access_subnets:
  - 80.193.85.91/32
  - 80.169.158.34/32
  vault_access_subnets:
  - 80.193.85.91/32
  - 80.169.158.34/32

prod:
  vpc_name: prod-vpc
  infra_stack_name: prod-infra
  etcd_volumes_stack_name: prod-coreos-etcd-volumes
  instance_type: t2.large
  dns_zone_name: dsp.digital.homeoffice.gov.uk
  platform_tls_cert_name: 'server-certificate/wildcard.dsp.digital.homeoffice.gov.uk'
  kms_master_key_id: 52933029-773a-49ba-af66-b8920d198175
  access_log_bucket_name: prod-elb-access-logs-eu-west-1
  secrets_bucket_name: prod-platform-secrets-eu-west-1
  # base64 encoded
  ca_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQvRENDQXVTZ0F3SUJBZ0lJRVNuaERkYnZ5QkF3RFFZSktvWklodmNOQVFFTEJRQXdnWWt4Q3pBSkJnTlYKQkFZVEFrZENNUnd3R2dZRFZRUUtFeE5JYjIxbElFOW1abWxqWlNCRWFXZHBkR0ZzTVIwd0d3WURWUVFMRXhSRQpVMUFnVUhKdlpDQkZiblpwY205dWJXVnVkREVQTUEwR0ExVUVCeE1HVEc5dVpHOXVNUTh3RFFZRFZRUUlFd1pNCmIyNWtiMjR4R3pBWkJnTlZCQU1URWtodmJXVWdUMlptYVdObElFUlRVQ0JEUVRBZUZ3MHhOVEE0TVRJeE5UQTEKTURCYUZ3MHlOVEE0TURreE5UQTFNREJhTUlHSk1Rc3dDUVlEVlFRR0V3SkhRakVjTUJvR0ExVUVDaE1UU0c5dApaU0JQWm1acFkyVWdSR2xuYVhSaGJERWRNQnNHQTFVRUN4TVVSRk5RSUZCeWIyUWdSVzUyYVhKdmJtMWxiblF4CkR6QU5CZ05WQkFjVEJreHZibVJ2YmpFUE1BMEdBMVVFQ0JNR1RHOXVaRzl1TVJzd0dRWURWUVFERXhKSWIyMWwKSUU5bVptbGpaU0JFVTFBZ1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDeAppTk9CTmt5ekY0VlZURERlTUtROUVJTEJ1UC9xbnRrZTM4SEtVMldOdHpiZnJMRFpjZ2oyRHkrNDZvVlArWGJECncvajNZQ0RiZm04cDduOGRab1FlSVlJRzMvaDRZc2dGcVNRdXhsMWFJc2pIY0kwZHJaNG1qa0t5WVg3di95eHIKeXNrWDJqUTJpSlM3NDN1MW5OWDg3MDBiSDFFK0lJQVBCd2J6ek5NVTF1elN6ZGNHS3d5VG40c0JkRktyNmt4UwpwVWt6K0J2US9RVWkvcHJDdHFPYVQzUGkwSU5wRmoveGtYY2x0TkNBbnRUdUxZelZLb3A5b3pjVkFITUhFc0tqClF3Y2owZTZZZFFRRkt3d1pNcEFKLzlwL0Z0NmYyN29oSnQ4TXFSb2h6YnBkYU00NUhNamZzWGt6RFRNYndmbm0KZ0RaQm5mYzQ5WHNYZzJmTmx3MDNBZ01CQUFHalpqQmtNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WSFJNQgpBZjhFQ0RBR0FRSC9BZ0VDTUIwR0ExVWREZ1FXQkJURTFjRU4zcytDeU1Rb3V6TERFWFYzSFErS25qQWZCZ05WCkhTTUVHREFXZ0JURTFjRU4zcytDeU1Rb3V6TERFWFYzSFErS25qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKRjFzUWlGVXNnS045MWd4d2xCY2paeVY4RzZuTUd3cHhNaWVZRHFXK2xhK2I5WEdsYlFUZTF4bnJxTUszUG5KcgpFaDRXNTA3TmtqVGV2MTdJZDB5ZU9TUWY4TmJNdjFjLzJlUmMwSTBjNXI0ejAxU0V4bUt4TTNPWTJhdUNOSEc0CnZrblJlR0Q2cFZMdWJ2ajFkWVhxS0hoRDljVEVKRHVQcHJmUDU4eE9hcm5scGdrZVpkRjFNVjdXV1RrZStDVE8KUmdNMjJKL0N5Y1lWT3JXa203eUhLNTQ4L2NMUGZqKzV5bHd5aTcxckdzVW1VZTBLZXNwNG1odmN3WDhpcmw3VgphQnJXYzhUVlU0aTNRTHBYQlBJWFNNc0UzMmJCUERuaXlmOGFFZTlkWXRIeU1MMzlMVFlvR1lUbGVKYUdMc0dlCk42UGllQ2F2S1V0Qi9ieEwrMzdxUlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

dev:
  vpc_name: dev-vpc
  infra_stack_name: dev-infra
  etcd_volumes_stack_name: dev-coreos-etcd-volumes
  instance_type: m4.2xlarge
  dns_zone_name: dsp.notprod.homeoffice.gov.uk
  platform_tls_cert_name: 'server-certificate/wildcard.notprod.homeoffice.gov.uk'
  kms_master_key_id: 448a33c3-694b-46fe-9635-4cfecff6877a
  secrets_bucket_name: dev-platform-secrets-eu-west-1
  access_log_bucket_name: dev-elb-access-logs-eu-west-1
  # base64 encoded
  ca_cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrakNDQXVLZ0F3SUJBZ0lJWEsxWXRRTzdSZVV3RFFZSktvWklodmNOQVFFTEJRQXdnWWd4Q3pBSkJnTlYKQkFZVEFrZENNUnd3R2dZRFZRUUtFeE5JYjIxbElFOW1abWxqWlNCRWFXZHBkR0ZzTVJ3d0dnWURWUVFMRXhORQpVMUFnUkdWMklFVnVkbWx5YjI1dFpXNTBNUTh3RFFZRFZRUUhFd1pNYjI1a2IyNHhEekFOQmdOVkJBZ1RCa3h2CmJtUnZiakViTUJrR0ExVUVBeE1TU0c5dFpTQlBabVpwWTJVZ1JGTlFJRU5CTUI0WERURTFNRGN5TURFNE1qWXcKTUZvWERUSTFNRGN4TnpFNE1qWXdNRm93Z1lneEN6QUpCZ05WQkFZVEFrZENNUnd3R2dZRFZRUUtFeE5JYjIxbApJRTltWm1salpTQkVhV2RwZEdGc01Sd3dHZ1lEVlFRTEV4TkVVMUFnUkdWMklFVnVkbWx5YjI1dFpXNTBNUTh3CkRRWURWUVFIRXdaTWIyNWtiMjR4RHpBTkJnTlZCQWdUQmt4dmJtUnZiakViTUJrR0ExVUVBeE1TU0c5dFpTQlAKWm1acFkyVWdSRk5RSUVOQk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNlkycQpSSjBDMlJwb0s0elhiWDhBMTNEVGRtRFRHUlZsd3kxQnpZTUpsQTRUelFRdGZrS2NRYzY5clZGUmkxN1hrQ0NxCk5XYW9IeHhqRTAvcnA3bDBueGNncGxWdURrMVZLSVhsemVKdVUzaWE2Ky9RWHI4M3lacENRRlBwK3N5R0pGeXIKMjFXa2NrK0xDdGJuN1I4Kzk0RzV4MzNNZWQyemg5SEczZG5DbHZlQWFJTlRhUnlTZU9Yb0RLRTVLUHZ2RlpxQwo4L0hQUzJCZWI4TFRXbFNQUWM3dHNMc3UxMy8rS3FhZXVtV2hZcVZXZDFHdiszc2JLUGZLcFlSRURlQXpGelpjCkVpa0tYWjQ0MjlDTHRSN1l4WkFKbFdoWFdrbDN2cDB4bStBd2VDMlNmajJsbjR5TGR5YjkxLy9oYnFkRUJwak0Ka09RZEZNNERibWFaNkdRKzRRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFILwpCQWd3QmdFQi93SUJBakFkQmdOVkhRNEVGZ1FVRTVDTnlUT21PYW9zbjY2clRQL3ozWDAwQW5rd0h3WURWUjBqCkJCZ3dGb0FVRTVDTnlUT21PYW9zbjY2clRQL3ozWDAwQW5rd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNYzkKUDhCL1JYREJZTjVtZyt5NjR4Zm4xR0drZUJCYUVVRTdjeHRYWEEyN2dSWVB5SUU5cENRdXI3YlMzWnQyMmtEMQp3SGlMUWdmb056Y2NYcTV2QUdPRGFYWVRTczVQMllnU2NMZ0xOVktGUnRtQWd4L2hJRDUxSFYzMTkwTDlnTDFSCm1NSXViUmczNDNTaWI4WElQQlorODhGZkhmUWd3TkpuK3F6NzRtWmpudi8rTTVoTFU4cXhrb24xTTFWQlhCVmIKTVU1cWtkOGw3SnZBMlJia0xrYWxMdks5U3NJTWJLQ3hwckRZY2thUjlHWGhnNUhsTlExWUd4Y1dHSWZVK1Z0aQp3RXVhY0tPRFQ3dlNKdko0YTl3WXBOREkwMEVUZDJVNXBQYVpLSVdqLy9XNSszMHNtL0h2Z3MwNmJTUE9nMDBOCjJvU1V6SGZiWjB4NkkxQWxqcnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
